name: Publish

on:
  push:
    branches:
      - main

permissions:
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Download Psychrolib
        run: wget 'https://raw.githubusercontent.com/psychrometrics/psychrolib/refs/heads/master/src/js/psychrolib.js'
      - name: Set NPM Token
        run: npm config set '//registry.npmjs.org/:_authToken' "${{ secrets.NPM_TOKEN }}"
      - name: Publish Package
        run: npm publish --provenance
